version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: apartment-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: apartment_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: apartment-backend
    ports:
      - '3333:3333'
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: apartment_db
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: apartment-frontend
    ports:
      - '3000:3000'
    environment:
      NEXT_PUBLIC_API_BASE_URL: 'http://localhost:3333'
    depends_on:
      - backend

volumes:
  mysql_data:
